import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-cream font-sans text-burgundy">
      <div className="max-w-4xl mx-auto px-6 md:px-12 py-12">
        <Link href="/" className="inline-flex items-center text-sm text-burgundy/60 hover:text-salmon mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Home
        </Link>
        
        <article className="prose prose-burgundy prose-lg max-w-none bg-white p-8 md:p-16 rounded-2xl shadow-xl border border-burgundy/5">
          <h1 className="text-3xl font-bold text-burgundy mb-6 pb-2 border-b border-burgundy/10">
            Terms and Conditions
          </h1>
          <p className="text-burgundy/60 mb-6">Last updated: December 2025</p>
          
          <div className="space-y-6 text-burgundy/80 leading-relaxed">
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing and using AgenticDeepSearch ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
              </p>
              <p>
                These Terms and Conditions ("Terms") govern your access to and use of our multi-agent deep research platform. Your use of the Service constitutes your acceptance of these Terms.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">2. Description of Service</h2>
              <p>
                AgenticDeepSearch is an autonomous multi-agent research platform that uses artificial intelligence to perform comprehensive web research, analyze information, and generate research reports. The Service utilizes third-party APIs including LinkUp for web search and OpenRouter for language model capabilities.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">3. Use of Service</h2>
              <h3 className="text-xl font-semibold text-burgundy/90 mt-6 mb-3">3.1 Permitted Use</h3>
              <p>You may use the Service for lawful purposes only. You agree to use the Service in accordance with all applicable laws and regulations.</p>
              
              <h3 className="text-xl font-semibold text-burgundy/90 mt-6 mb-3">3.2 Prohibited Activities</h3>
              <p>You agree not to:</p>
              <ul className="list-disc list-outside ml-6 space-y-2 mb-4">
                <li>Use the Service for any illegal or unauthorized purpose</li>
                <li>Attempt to gain unauthorized access to the Service or its related systems</li>
                <li>Interfere with or disrupt the Service or servers connected to the Service</li>
                <li>Use the Service to generate harmful, abusive, or offensive content</li>
                <li>Attempt to reverse engineer, decompile, or disassemble the Service</li>
                <li>Use automated systems to access the Service in a manner that exceeds reasonable usage limits</li>
                <li>Submit queries that contain malicious code, viruses, or other harmful components</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">4. User Responsibilities</h2>
              <p>You are responsible for:</p>
              <ul className="list-disc list-outside ml-6 space-y-2 mb-4">
                <li>Maintaining the confidentiality of any account credentials</li>
                <li>All activities that occur under your account</li>
                <li>Ensuring the accuracy and legality of queries you submit</li>
                <li>Verifying the accuracy and appropriateness of research results before use</li>
                <li>Complying with all applicable laws and regulations when using research results</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">5. Intellectual Property</h2>
              <h3 className="text-xl font-semibold text-burgundy/90 mt-6 mb-3">5.1 Service Ownership</h3>
              <p>
                The Service, including its original content, features, and functionality, is owned by AgenticDeepSearch and is protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
              </p>
              
              <h3 className="text-xl font-semibold text-burgundy/90 mt-6 mb-3">5.2 Research Results</h3>
              <p>
                Research results generated by the Service are provided for your use. However, you acknowledge that:
              </p>
              <ul className="list-disc list-outside ml-6 space-y-2 mb-4">
                <li>Results may contain information from third-party sources</li>
                <li>You are responsible for verifying the accuracy of information</li>
                <li>You must respect the intellectual property rights of source materials</li>
                <li>Results should not be used in violation of any third-party rights</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">6. Service Availability and Modifications</h2>
              <p>
                We reserve the right to modify, suspend, or discontinue the Service (or any part thereof) at any time, with or without notice. We do not guarantee that the Service will be available at all times or that it will be error-free.
              </p>
              <p>
                We may update, change, or modify the Service's features and functionality at our sole discretion. Your continued use of the Service after such changes constitutes acceptance of the modified Service.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">7. Limitation of Liability</h2>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, AGENTICDEEPSEARCH SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.
              </p>
              <p>
                The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that:
              </p>
              <ul className="list-disc list-outside ml-6 space-y-2 mb-4">
                <li>The Service will be uninterrupted, secure, or error-free</li>
                <li>Research results will be accurate, complete, or reliable</li>
                <li>Defects will be corrected</li>
                <li>The Service is free of viruses or other harmful components</li>
              </ul>
              <p>
                You acknowledge that research results are generated using AI and may contain inaccuracies. You are solely responsible for verifying and validating any information obtained through the Service.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">8. Indemnification</h2>
              <p>
                You agree to indemnify, defend, and hold harmless AgenticDeepSearch, its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including reasonable attorneys' fees, arising out of or in any way connected with your use of the Service or violation of these Terms.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">9. Termination</h2>
              <p>
                We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason, including if you breach these Terms.
              </p>
              <p>
                Upon termination, your right to use the Service will cease immediately. All provisions of these Terms which by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, and limitations of liability.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">10. Rate Limiting and Usage</h2>
              <p>
                The Service implements rate limiting to ensure fair usage and system stability. You agree to comply with any usage limits and not to attempt to circumvent rate limiting mechanisms. Excessive usage may result in temporary or permanent suspension of access.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">11. Third-Party Services</h2>
              <p>
                The Service integrates with third-party services and APIs. Your use of these third-party services is subject to their respective terms and conditions. We are not responsible for the availability, accuracy, or content of third-party services.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">12. Governing Law</h2>
              <p>
                These Terms shall be governed by and construed in accordance with applicable laws, without regard to its conflict of law provisions. Any disputes arising from these Terms or the Service shall be subject to the exclusive jurisdiction of the appropriate courts.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">13. Changes to Terms</h2>
              <p>
                We reserve the right to modify these Terms at any time. We will notify users of any material changes by posting the updated Terms on this page and updating the "Last updated" date. Your continued use of the Service after such modifications constitutes acceptance of the updated Terms.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">14. Severability</h2>
              <p>
                If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-burgundy mt-8 mb-4">15. Contact Information</h2>
              <p>
                If you have any questions about these Terms and Conditions, please contact us:
              </p>
              <div className="bg-salmon/5 p-4 rounded-lg mt-4 border-l-4 border-salmon/50">
                <p className="mb-2"><strong>Email:</strong> legal@agenticdeepsearch.com</p>
                <p className="mb-2"><strong>Website:</strong> <a href="https://researcherai.apexneural.cloud" className="text-salmon hover:underline">https://researcherai.apexneural.cloud</a></p>
              </div>
            </section>
          </div>
        </article>
        
        {/* Footer */}
        <footer className="mt-16 pt-8 border-t border-burgundy/10">
          <div className="max-w-4xl mx-auto px-6 md:px-12">
            <div className="text-center text-sm text-burgundy/60">
              <p className="mb-2">© 2025 ApexNeural. All rights reserved.</p>
              <div className="flex justify-center gap-6">
                <Link href="/privacy" className="hover:text-salmon transition-colors">Privacy Policy</Link>
                <Link href="/terms" className="hover:text-salmon transition-colors">Terms of Service</Link>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
  );
}

